# This is a basic workflow that is manually triggered

name: Install TestCafe
on:
  workflow_dispatch:

jobs:
  build-testcafe:
    runs-on: ubuntu-20.04
    steps:
      - uses: browser-actions/setup-chrome@latest
      - uses: actions/checkout@v2
      - name: Install nodeJS
        run: sudo apt-get update && sudo apt-get -y install nodejs
      - name: Install NPM
        run: sudo apt-get install npm && nodejs -v
      - name: Install TestCafe
        run: npm install -g testcafe
      - name: Run TestCafe Tests
        #run: testcafe --list-browsers
        run: testcafe chrome:/opt/hostedtoolcache/chromium/latest/x64:headless --skip-js-errors --speed 0.75 --browser-init-timeout 180000 scripts/theme-designer.js 
