# This is a basic workflow that is manually triggered

name: Install TestCafe
on:
  workflow_dispatch:

jobs:
  build-testcafe:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install nodeJS
        run: sudo apt-get update && sudo apt-get -y install nodejs
      - name: Install NPM
        run: sudo apt-get install npm && nodejs -v
